### PR TITLE
Allow `load_vre_stor_variability!` to load only wind or solar variabilities

### LINKED ISSUE #727: [Bug]: VRE_STOR asks for both wind and solar variability data when there is only solar or wind components in VRE_STOR.
### Bug description

I only have WIND component in VRE_STOR but GenX still asks for "Vre_and_stor_solar_variability.csv".

The error is caused by the lack of checking the existence of "WIND" or "SOLAR" component in load_vre_stor_variability.jl

### Environment and Version

GenX 0.4

### Relevant error messages

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lbonaldo**
## Description

This PR allows the function `load_vre_stor_variability!` to load only wind or solar variability if only "SOLAR" or "WIND" resources are present in the system. 

## What type of PR is this? (check all applicable)

- [x] Bug Fix
- [x] Code Refactor

## Related Tickets & Documents
Fixes #727

## Checklist

- [x] Code changes are sufficiently documented; i.e. new functions contain docstrings and .md files under /docs/src have been updated if necessary.
- [X] The latest changes on the target branch have been incorporated, so that any conflicts are taken care of before merging. This can be accomplished either by merging in the target branch (e.g. 'git merge develop') or by rebasing on top of the target branch (e.g. 'git rebase develop'). Please do not hesitate to reach out to the GenX development team if you need help with this.
- [X] Code has been tested to ensure all functionality works as intended.
- [x] CHANGELOG.md has been updated (if this is a 'notable' change).
- [X] I consent to the release of this PR's code under the GNU General Public license.

## How this can be tested
This fix can be tested by running the `7_three_zones_w_colocated_VRE_storage` example case and removing all SOLAR resources together with the `Vre_and_stor_solar_variability.csv` file. Alternatively, it can be tested by running the new test cases within the `test/VRE_storage folder`.

## Post-approval checklist for GenX core developers
After the PR is approved

- [x] Check that the latest changes on the target branch are incorporated, either via merge or rebase
- [x] Remember to squash and merge if incorporating into develop

### CODE REVIEW

**Review by sambuddhac — COMMENTED** [review]
What's the rationale behind regrouping the stuff inside ensure_column_zeros into ensure_column_zeros and load_process_variability ?

**Review by sambuddhac — APPROVED** [review]
Reviewed and approved !!!

**Comment by lbonaldo** [comment]
> What's the rationale behind regrouping the stuff inside ensure_column_zeros into ensure_column_zeros and load_process_variability ?

Hey @sambuddhac, I moved `ensure_column_zeros` outside of `load_vre_stor_variability!` so that it can be called by other functions. `load_process_variability` now wraps the code to separately load the variability files for solar and wind.

**Comment by lbonaldo** [comment]
> Reviewed and approved !!!

Thank you @sambuddhac!

**Pull request merged**
